USE [master]
GO

/****** Object:  Database [ValhallaDatabase]    Script Date: 07/02/2020 17:05:32 ******/
CREATE DATABASE [ValhallaDatabase]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ValhallaDatabase', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER17\MSSQL\DATA\ValhallaDatabase.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ValhallaDatabase_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER17\MSSQL\DATA\ValhallaDatabase_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [ValhallaDatabase] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ValhallaDatabase].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ValhallaDatabase] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ValhallaDatabase] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ValhallaDatabase] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ValhallaDatabase] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ValhallaDatabase] SET ARITHABORT OFF 
GO

ALTER DATABASE [ValhallaDatabase] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ValhallaDatabase] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ValhallaDatabase] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ValhallaDatabase] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ValhallaDatabase] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ValhallaDatabase] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ValhallaDatabase] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ValhallaDatabase] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ValhallaDatabase] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ValhallaDatabase] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ValhallaDatabase] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ValhallaDatabase] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ValhallaDatabase] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ValhallaDatabase] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ValhallaDatabase] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ValhallaDatabase] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ValhallaDatabase] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ValhallaDatabase] SET RECOVERY FULL 
GO

ALTER DATABASE [ValhallaDatabase] SET  MULTI_USER 
GO

ALTER DATABASE [ValhallaDatabase] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ValhallaDatabase] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ValhallaDatabase] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ValhallaDatabase] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [ValhallaDatabase] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ValhallaDatabase] SET QUERY_STORE = OFF
GO

ALTER DATABASE [ValhallaDatabase] SET  READ_WRITE 
GO


